[project]
name = "kiira2api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "requests>=2.32.5",
    "httpx>=0.27.0",
    "uvicorn[standard]>=0.38.0",
    "pydantic-settings>=2.0.0",
]
